// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cftransmodel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CftransModel _$CftransModelFromJson(Map<String, dynamic> json) => CftransModel(
      id: json['id'] as int?,
      date: json['date'] as String?,
      chiti: json['chiti'] as int?,
      paata: json['paata'] as int?,
      customer: json['customer'] as int?,
      debit: json['debit'] as int?,
      credit: json['credit'] as int?,
      paymentmode: json['paymentmode'] as int?,
      pmid: json['pmid'] as String?,
      note: json['note'] as String?,
      cusno: json['cusno'] as int?,
      fname: json['fname'] as String?,
      lname: json['lname'] as String?,
      phone: json['phone'] as String?,
      first: json['first'] as int?,
      firstid: json['firstid'] as int?,
      maincus: json['maincus'] as int?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      phoneno: json['phoneno'] as String?,
      hami: json['hami'] as int?,
      ishami: json['ishami'] as int?,
      chitfund: json['chitfund'] as int?,
      aadhar: json['aadhar'] as int?,
      passbook: json['passbook'] as int?,
      debitcard: json['debitcard'] as int?,
      cheque: json['cheque'] as int?,
      pnote: json['pnote'] as int?,
      greensheet: json['greensheet'] as int?,
      forint: json['forint'] as int?,
      intrate: json['intrate'] as int?,
      chitiname: json['chitiname'] as String?,
      code: json['code'] as String?,
      no: json['no'] as int?,
      amount: json['amount'] as int?,
      payamount: json['payamount'] as int?,
      repayamount: json['repayamount'] as int?,
      sripalcomm: json['sripalcomm'] as int?,
      sowjicomm: json['sowjicomm'] as int?,
      customername: json['customername'] as String?,
      paatano: json['paatano'] as int?,
      paataamt: json['paataamt'] as int?,
    );

Map<String, dynamic> _$CftransModelToJson(CftransModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'date': instance.date,
      'chiti': instance.chiti,
      'paata': instance.paata,
      'customer': instance.customer,
      'debit': instance.debit,
      'credit': instance.credit,
      'paymentmode': instance.paymentmode,
      'pmid': instance.pmid,
      'note': instance.note,
      'cusno': instance.cusno,
      'fname': instance.fname,
      'lname': instance.lname,
      'phone': instance.phone,
      'first': instance.first,
      'firstid': instance.firstid,
      'maincus': instance.maincus,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'phoneno': instance.phoneno,
      'hami': instance.hami,
      'ishami': instance.ishami,
      'chitfund': instance.chitfund,
      'aadhar': instance.aadhar,
      'passbook': instance.passbook,
      'debitcard': instance.debitcard,
      'cheque': instance.cheque,
      'pnote': instance.pnote,
      'greensheet': instance.greensheet,
      'forint': instance.forint,
      'intrate': instance.intrate,
      'chitiname': instance.chitiname,
      'code': instance.code,
      'no': instance.no,
      'amount': instance.amount,
      'payamount': instance.payamount,
      'repayamount': instance.repayamount,
      'sripalcomm': instance.sripalcomm,
      'sowjicomm': instance.sowjicomm,
      'customername': instance.customername,
      'paatano': instance.paatano,
      'paataamt': instance.paataamt,
    };
