// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chitilistModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ChitilistModel _$ChitilistModelFromJson(Map<String, dynamic> json) =>
    ChitilistModel(
      id: json['id'] as int?,
      customer: json['customer'] as int?,
      code: json['code'] as String?,
      date: json['date'] as String?,
      tYpe: json['tYpe'] as int?,
      advintmonths: json['advintmonths'] as int?,
      iscountable: json['iscountable'] as int?,
      amount: json['amount'] as int?,
      paymentmode: json['paymentmode'] as int?,
      pmid: json['pmid'] as String?,
      pdwtm: json['pdwtm'] as int?,
      interestrate: json['interestrate'] as String?,
      ccomm: json['ccomm'] as int?,
      ccommpaymentmode: json['ccommpaymentmode'] as int?,
      suriccomm: json['suriccomm'] as int?,
      sowji: json['sowji'] as int?,
      suri: json['suri'] as int?,
      fullandevi: json['fullandevi'] as int?,
      reverse: json['reverse'] as int?,
      revcash: json['revcash'] as int?,
      status: json['status'] as int?,
      note: json['note'] as String?,
      irregular: json['irregular'] as int?,
      created: json['created'] as String?,
      updated: json['updated'] as String?,
      deleted: json['deleted'] as int?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      phoneno: json['phoneno'] as String?,
      hami: json['hami'] as int?,
      ishami: json['ishami'] as int?,
      chitfund: json['chitfund'] as int?,
      aadhar: json['aadhar'] as int?,
      passbook: json['passbook'] as int?,
      debitcard: json['debitcard'] as int?,
      cheque: json['cheque'] as int?,
      pnote: json['pnote'] as int?,
      greensheet: json['greensheet'] as int?,
      forint: json['forint'] as int?,
      intrate: json['intrate'] as int?,
      modename: json['modename'] as String?,
      opbal: json['opbal'] as int?,
      customername: json['customername'] as String?,
      haminame: json['haminame'] as String?,
      paymentmodename: json['paymentmodename'] as String?,
      ccommpaymentmodename: json['ccommpaymentmodename'] as String?,
    );

Map<String, dynamic> _$ChitilistModelToJson(ChitilistModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'customer': instance.customer,
      'code': instance.code,
      'date': instance.date,
      'tYpe': instance.tYpe,
      'advintmonths': instance.advintmonths,
      'iscountable': instance.iscountable,
      'amount': instance.amount,
      'paymentmode': instance.paymentmode,
      'pmid': instance.pmid,
      'pdwtm': instance.pdwtm,
      'interestrate': instance.interestrate,
      'ccomm': instance.ccomm,
      'ccommpaymentmode': instance.ccommpaymentmode,
      'suriccomm': instance.suriccomm,
      'sowji': instance.sowji,
      'suri': instance.suri,
      'fullandevi': instance.fullandevi,
      'reverse': instance.reverse,
      'revcash': instance.revcash,
      'status': instance.status,
      'note': instance.note,
      'irregular': instance.irregular,
      'created': instance.created,
      'updated': instance.updated,
      'deleted': instance.deleted,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'phoneno': instance.phoneno,
      'hami': instance.hami,
      'ishami': instance.ishami,
      'chitfund': instance.chitfund,
      'aadhar': instance.aadhar,
      'passbook': instance.passbook,
      'debitcard': instance.debitcard,
      'cheque': instance.cheque,
      'pnote': instance.pnote,
      'greensheet': instance.greensheet,
      'forint': instance.forint,
      'intrate': instance.intrate,
      'modename': instance.modename,
      'opbal': instance.opbal,
      'customername': instance.customername,
      'haminame': instance.haminame,
      'paymentmodename': instance.paymentmodename,
      'ccommpaymentmodename': instance.ccommpaymentmodename,
    };
