// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'receivedList.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ReceivedList _$ReceivedListFromJson(Map<String, dynamic> json) => ReceivedList(
      id: json['id'] as int?,
      customer: json['customer'] as int?,
      amount: json['amount'] as int?,
      rcvddate: json['rcvddate'] as String?,
      asalu: json['asalu'] as int?,
      asaluid: json['asaluid'] as int?,
      chiti: json['chiti'] as int?,
      colid: json['colid'] as int?,
      paymentmode: json['paymentmode'] as int?,
      pmid: json['pmid'] as String?,
      note: json['note'] as String?,
      created: json['created'] as String?,
      updated: json['updated'] as String?,
      deleted: json['deleted'] as int?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      phoneno: json['phoneno'] as String?,
      hami: json['hami'] as int?,
      ishami: json['ishami'] as int?,
      chitfund: json['chitfund'] as int?,
      aadhar: json['aadhar'] as int?,
      passbook: json['passbook'] as int?,
      debitcard: json['debitcard'] as int?,
      cheque: json['cheque'] as int?,
      pnote: json['pnote'] as int?,
      greensheet: json['greensheet'] as int?,
      forint: json['forint'] as int?,
      intrate: json['intrate'] as int?,
      date: json['date'] as String?,
      notes: json['notes'].toString() as String?,
      sowji: json['sowji'] as int?,
      suri: json['suri'] as int?,
      fullandevi: json['fullandevi'] as int?,
      received: json['received'] as int?,
      reverseid: json['reverseid'] as int?,
      receivedfrom: json['receivedfrom'] as int?,
      code: json['code'] as String?,
      tYpe: json['tYpe'] as int?,
      advintmonths: json['advintmonths'] as int?,
      iscountable: json['iscountable'] as int?,
      pdwtm: json['pdwtm'] as int?,
      interestrate: json['interestrate'] as String?,
      ccomm: json['ccomm'] as int?,
      ccommpaymentmode: json['ccommpaymentmode'] as int?,
      suriccomm: json['suriccomm'] as int?,
      reverse: json['reverse'] as int?,
      revcash: json['revcash'] as int?,
      status: json['status'] as int?,
      irregular: json['irregular'] as int?,
      chitiamount: json['chitiamount'] as int?,
      modename: json['modename'] as String?,
      opbal: json['opbal'] as int?,
      customername: json['customername'] as String?,
      paymentmodename: json['paymentmodename'] as String?,
      colamt: json['colamt'] as int?,
      sowjicomm: json['sowjicomm'] as int?,
      suricomm: json['suricomm'] as int?,
      fullandevicomm: json['fullandevicomm'] as int?,
      asaluchiti: json['asaluchiti'] as int?,
      coldate: json['coldate'] as String?,
    );

Map<String, dynamic> _$ReceivedListToJson(ReceivedList instance) =>
    <String, dynamic>{
      'id': instance.id,
      'customer': instance.customer,
      'amount': instance.amount,
      'rcvddate': instance.rcvddate,
      'asalu': instance.asalu,
      'asaluid': instance.asaluid,
      'chiti': instance.chiti,
      'colid': instance.colid,
      'paymentmode': instance.paymentmode,
      'pmid': instance.pmid,
      'note': instance.note,
      'created': instance.created,
      'updated': instance.updated,
      'deleted': instance.deleted,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'phoneno': instance.phoneno,
      'hami': instance.hami,
      'ishami': instance.ishami,
      'chitfund': instance.chitfund,
      'aadhar': instance.aadhar,
      'passbook': instance.passbook,
      'debitcard': instance.debitcard,
      'cheque': instance.cheque,
      'pnote': instance.pnote,
      'greensheet': instance.greensheet,
      'forint': instance.forint,
      'intrate': instance.intrate,
      'date': instance.date,
      'notes': instance.notes,
      'sowji': instance.sowji,
      'suri': instance.suri,
      'fullandevi': instance.fullandevi,
      'received': instance.received,
      'reverseid': instance.reverseid,
      'receivedfrom': instance.receivedfrom,
      'code': instance.code,
      'tYpe': instance.tYpe,
      'advintmonths': instance.advintmonths,
      'iscountable': instance.iscountable,
      'pdwtm': instance.pdwtm,
      'interestrate': instance.interestrate,
      'ccomm': instance.ccomm,
      'ccommpaymentmode': instance.ccommpaymentmode,
      'suriccomm': instance.suriccomm,
      'reverse': instance.reverse,
      'revcash': instance.revcash,
      'status': instance.status,
      'irregular': instance.irregular,
      'chitiamount': instance.chitiamount,
      'modename': instance.modename,
      'opbal': instance.opbal,
      'customername': instance.customername,
      'paymentmodename': instance.paymentmodename,
      'colamt': instance.colamt,
      'sowjicomm': instance.sowjicomm,
      'suricomm': instance.suricomm,
      'fullandevicomm': instance.fullandevicomm,
      'asaluchiti': instance.asaluchiti,
      'coldate': instance.coldate,
    };
